### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by joren485** [thaliawww/sentry-thalia#6]
```
$ docker build --no-cache .
Sending build context to Docker daemon  44.03kB
Step 1/1 : FROM sentry:onbuild
# Executing 4 build triggers
 ---> Running in 1f59db097e35
Removing intermediate container 1f59db097e35
 ---> Running in 2d21e7fb4b3a
Obtaining file:///usr/src/sentry
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 193, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 329, in prepare_editable_requirement
    req.check_if_exists(use_user_site)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 350, in check_if_exists
    self.req.name
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 476, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 352, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (redis 2.10.5 (/usr/local/lib/python2.7/site-packages), Requirement.parse('redis==2.10.6'), set(['redis-py-cluster']))
The command '/bin/sh -c if [ -s setup.py ]; then pip install -e .; fi' returned a non-zero code: 2
```

**Comment by joren485** [comment]
It looks like this is fixed up stream (https://github.com/getsentry/sentry/pull/9177).
